### PR TITLE
Added write routine for Raspberry Pi 4

### PR DESCRIPTION
**Pull request by mav2010**
Hi,

thanks for the great work you have done here. I have modded a Corona 16MB XBOX 360 in the last few days and based on your code enhanced it to also write to the NAND. Using a Raspberry Pi 4 with Raspbian Lite, I didn't have a single read or write error. :-)

If you need more information or want me to compile a small README with wiring instructions etc., please let me know. A little bit of info I have added to my [Readme](https://github.com/mav2010/xbox360-rpi-flasher/blob/master/README.md).

Thanks,
mav2010

### CODE REVIEW

**Comment by Ancient123** [comment]
Awesome! Good work!

**Comment by walczakp** [comment]
Hey, this is awesome! Great work. I can't test this myself as I don't have RPi 4, but I will happily merge your PR. It would be super cool if you could update the readme in this PR, so that others can more easily benefit from your change.

**Comment by mav2010** [comment]
OK, new commit with updated README is pushed. I included a short tutorial. I didn't bother to program proper parameters, so it is all a bit manual. :-)

**Comment by walczakp** [comment]
Thank you so much for all of this. Excellent write-up. Such a manual-ish way to make it work is even better imo, it requires more care from the user, which is good for a solution that was not tested extensively. I'm sure this will help some people already having a powerful Pi at hand.

**Comment by mav2010** [comment]
You are more than welcome. Thank you for the very good basis. Effectively, all of your code in XNAND and XSPI worked from the start. It was basically just a question of using it in the right way. But timing etc. all worked form the start. I was super hyped that it actually just worked in the end (after a few rounds of debugging my code by studying the dumped file in a hex editor...).

**Pull request merged**
